### ISSUE TITLE
Session doesn't resume

### ISSUE THREAD

**Issue by jaredmoody** [blackcandy-org/black_candy_ios#3]
After a while of inactivity, the app just loads a white blank screen. Closing the app and re-opening loads the page.

**Comment by joemasilotti** [comment]
I see that you are trying to reload the session when the web view process dies.

```swift
```

**Comment by aidewoode** [comment]
I have been using the app for a while now. And I didn't experience this issue any more. I think this issue has already  been fixed. So I am going to close this issue.
